//USEUNIT RefLibrary

var splitbutton = "//button[@icon='pi pi-chevron-down']"
var ProjectName = "//*[@name='projectName']"
var Decription = "//*[@name='description']"
var DefaultAssetApproval = "//*[@name='assetApprovalProcess']"
var DefaultFactTypeApproval = "//*[@name='factTypeApprovalProcess']"
var TaskName = "//input[@name='taskName']"
var TagName = "//*[@name='tagName']"
var row = "//tbody/tr"
var ulliTags = "//ul//li"
var dcnComboBox = "//dcn-combo-box"
var dcnAutoComplete = "//dcn-autocomplete"
var dcnAssetDisplay = "//dcn-asset-display"
var dcnLaundryLine = "//dcn-laundry-line"
var dcnHoverBtn = "//dcn-hover-button"
var dcnDialog = "//dcn-dialog"
var dcnRevisionEnv = "//dcn-revision-environment"
var dcnEnvDialog = "//dcn-environments-dialog"
var wjComboBox = "//wj-combo-box"
var newAssignee = "[@name='assignee']"
var clsLabelDraft = "//span[contains(@class,'label--draft')]"
var newUserName = "//input[@name='userName']"

//----------------------------------------------------------------
var ModelingPrjName = "//*[@name='project']"
var AssetApproval = "//*[@name='approvalProcess']"
var FtApproval = "//*[@name='ftApprovalProcess']"
var btnCreateOpen = "//*[contains(text(), 'Create & Open')]"
var btnCreateStart = "//*[contains(text(), 'Create & Start')]"
var liRolePresentation = "//li[@role='presentation']"
var roleTreeItem = "//*[@role='treeitem']"

//----------------------------------------------------------------
var DecisionName = "//*[@name='decisionName']"
var ViewName = "//*[@name='viewName']"
var FolderName = "//*[@name='folder']"
var placeholderName = "//*[@placeholder='column name']"
var community = "[@name='community']"
var newCommunity = "[@name='Community']"

//--------Fact type-------------------------
var FactTypeSummary = "//h1[contains(text(), 'Fact Type Summary:')]"
var ftName = "//*[@name='name']"
var lblSingleValue = "//*[@aria-label='Single Value']"
var lblMultipleValue = "//*[@aria-label='Multiple Values']"
var ftDataType = "//*[@name='dataType']"
var ftDisplayFormat = "//*[@name='displayFormat']"
var ftAllowedValues = "//*[@name='allowedValues']"
var dcnPlaceholderFrom = "//dcn-domain-input[@placeholder='from']"
var dcnPlaceholderTo = "//dcn-domain-input[@placeholder='to']"
var PlaceholderFrom = "//input[@placeholder='from']"
var PlaceholderTo = "//input[@placeholder='to']"
var PlaceholderAddValue = "//input[@placeholder='Add a value']"
var datePickFrom = "//*[@placeholder='from']//*[@wj-part='btn']"
var datePickTo = "//*[@placeholder='to']//*[@wj-part='btn']"
var nameValue = "//*[@name='value']"
var btnAdd = "//button[contains(@class,'add-btn')]"
var drpdwnPriority = "//*[@name='priority']"
var GroupLabel = "//*[@name='groupingLabel']"

//----------------------------------------------------------------
var tblFrozenView = "//*[contains(@class,'table-frozen-view')]"
var pTblFrozenView = "//*[contains(@class,'p-datatable-frozen-view')]"
var tblUnfrozenView = "//*[contains(@class,'datatable-unfrozen-view')]"